// Code generated by "stringer -type=Mode"; DO NOT EDIT.

package primitive

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeCombo-0]
	_ = x[ModeTriangle-1]
	_ = x[ModeRectangle-2]
	_ = x[ModeEllipse-3]
	_ = x[ModeCircle-4]
	_ = x[ModeRotatedRectangle-5]
	_ = x[ModeBeziers-6]
	_ = x[ModeRotatedEllipse-7]
	_ = x[ModePolygon-8]
}

const _Mode_name = "ModeComboModeTriangleModeRectangleModeEllipseModeCircleModeRotatedRectangleModeBeziersModeRotatedEllipseModePolygon"

var _Mode_index = [...]uint8{0, 9, 21, 34, 45, 55, 75, 86, 104, 115}

func (i Mode) String() string {
	if i < 0 || i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
